name: Waka Readme

on:
  schedule:
    # Runs
    - cron: '0 */6 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: true
          SHOW_PROJECTS: false
          SHOW_TIMELINE: true
          SHOW_LOC_CHART: true
          "SHOW_LINES_OF_CODE": true
          "SHOW_TOTAL_CODE_TIME": true
          "SHOW_PROFILE_VIEWS": true
          "SHOW_TIMEZONE": true
          "SHOW_SHORT_INFO": true
